<!-- Font CSS -->
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" />

<!-- Core CSS -->
<link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/fonts/glyphicons_pro/glyphicons.min.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/fonts/icomoon/style.css" />

<!-- Core CSS - via Local Storage 
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/core/bootstrap.min.css">-->

<!-- Plugin CSS -->
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/calendar/fullcalendar.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/datatables/css/datatables.min.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/animate.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/datatables/extras/TableTools/media/css/TableTools.css"/><!-- Datatables TableTools Addon-->
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/editors/xeditable/css/bootstrap-editable.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/chosen/chosen.min.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/colorpicker/colorpicker.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/datepicker/datepicker.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/vendor/plugins/daterange/daterangepicker.css" />


<!-- Theme CSS -->
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/theme.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/pages.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/plugins.css" />
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/responsive.css" />

<!-- Demo CSS -->
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/demo.css" />

<!-- Global Custom Styles -->
<link rel="stylesheet" type="text/css" href="/skin/default/theme_stardom/css/custom.css" />