<!-- Core Javascript - via CDN -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script> 


<!-- Core Javascript - via Local Storage 
<script src="/skin/default/theme_stardom/vendor/core/jquery.min.js"></script>
<script src="/skin/default/theme_stardom/vendor/core/jquery-ui.min.js"></script>
<script src="/skin/default/theme_stardom/vendor/core/bootstrap.min.js"></script> -->

<!-- Plugins - Via CDN -->
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.1/jquery.flot.min.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>


<!-- Plugins - Via Local Storage 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/jqueryflot/jquery.flot.min.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/sparkline/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/calendar/fullcalendar.min.js"></script>
-->

<!-- Plugins -->
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/calendar/gcal.js"></script><!-- Calendar Addon -->
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/jqueryflot/jquery.flot.resize.min.js"></script><!-- Flot Charts Addon -->
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/datatables/js/datatables.js"></script><!-- Datatable Bootstrap Addon -->
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/validate/jquery.validate.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/tags/tagmanager.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/formswitch/js/bootstrap-switch.min.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/editors/xeditable/js/bootstrap-editable.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/chosen/chosen.jquery.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/daterange/moment.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/daterange/daterangepicker.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/colorpicker/bootstrap-colorpicker.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/timepicker/bootstrap-timepicker.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/datepicker/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/formswitch/js/bootstrap-switch.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/vendor/plugins/jquerymask/jquery.maskedinput.min.js"></script> 


<!-- Theme Javascript --> 
<script type="text/javascript" src="/skin/default/theme_stardom/js/uniform.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/js/main.js"></script>

<!-- Global Custom Javascript -->
<script type="text/javascript" src="/skin/default/theme_stardom/js/custom.js"></script> 