

<form class="cmxform" id="passwordUpdateForm"
	method="<?php echo $this->element->getMethod() ?>"
	name="<?php echo $this->element->getName() ?>"
	action="<?php echo $this->element->getAction() ?>">

	<div class="panel-body">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><span
					class="glyphicons glyphicons-lock"></span></span> <input
					type="password" class="form-control" maxlength="100"
					autocomplete="off" name="currentPassword" id="currentPassword"
					placeholder="<?= $this->T('Current password')?>">
			</div>
			<span class="help-block margin-top-sm"><i
				class="glyphicons glyphicons-up_arrow"></i> <?= $this->T('Front:PasswordUpdateCurrentPasswordTip')?></span>
		</div>

		<div class="form-group">
			<input type="password" class="form-control" maxlength="100"
				autocomplete="off" name="newPassword" id="newPassword"
				placeholder="<?= $this->T('New password')?>">
		</div>

		<?= $this->render('/_widgets/passwordStrengthMeter.phtml') ?>

		<div class="form-group">
			<input type="password" class="form-control" maxlength="100"
				autocomplete="off" name="confirmPassword" id="confirmPassword"
				placeholder="<?= $this->T('Confirm password')?>" required>
		</div>
		
		<?php foreach ($this->element->getMessages() as $error) echo $this->formErrors($error);?>

	</div>
	<div class="panel-footer">
		<div class="form-group margin-bottom-none">
			<button type="submit" id="submit"
				class="btn btn-primary btn-gradient pull-right" name="update"><?= $this->T('Update')?></button>
			<div class="clearfix"></div>
		</div>
	</div>
</form>
