<div class="container">
<div class="panel">
            <div class="panel-heading">
              <div class="panel-title"> <i class="fa fa-pencil"></i>Standard Portlet</div>
            </div>
            <div class="panel-body">
              <p></p>
            </div>
          </div>
<!-- <?php echo $this->navigation()->menu()->renderMenu($this->zendNavigationContainer) ?>-->
    <?php echo $this->navigation()->menu();?>
</div>