<?php // meta.phtml ?>

<meta http-equiv="Content-Type" content="<?= $this->escape($this->ContentType) ?>" />
<meta name="keywords" content="<?= $this->escape($this->keywords) ?>" />
<meta name="description" content="<?= $this->escape($this->description) ?>" />
<meta name="author" content="<?= $this->escape($this->author) ?>" />
<meta name="viewport" content="<?= $this->escape($this->viewport) ?>" />