<aside id="sidebar">
    <div id="sidebar-search">
      <form role="search">
        <input type="text" class="search-bar form-control" placeholder="Search">
        <i class="fa fa-search field-icon-right"></i>
        <button type="submit" class="btn btn-default hidden"></button>
      </form>
      <div class="sidebar-toggle"> <i class="fa fa-bars"></i> </div>
    </div>
    <div id="sidebar-menu">
      <ul class="nav sidebar-nav">
        <li> <a href="portlets.html"><span class="glyphicons glyphicons-sort"></span><span class="sidebar-title">Portlets</span></a> </li>
        <li> <a href="dashboard.html"><span class="glyphicons glyphicons-star"></span><span class="sidebar-title">Dashboard</span></a> </li>
        <li> <a class="accordion-toggle" href="#resources"><span class="glyphicons glyphicons-settings"></span><span class="sidebar-title">Resources</span><span class="caret"></span></a>
          <ul id="resources" class="nav sub-nav">
            <li><a href="customizer.html"><span class="glyphicons glyphicons-edit"></span> Theme Customizer</a></li>
            <li><a href="skin-demo.html"><span class="glyphicons glyphicons-magic"></span> Demo Style Switcher </a></li>
            <li><a href="documentation/index.html"><span class="glyphicons glyphicons-book"></span> Documentation </a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideOne"><span class="glyphicons glyphicons-adjust_alt"></span><span class="sidebar-title">UI Elements</span><span class="caret"></span></a>
          <ul id="sideOne" class="nav sub-nav">
            <li><a href="buttons.html"><span class="glyphicons glyphicons-macbook"></span> Buttons</a></li>
            <li><a href="typography.html"><span class="glyphicons glyphicons-font"></span> Typography</a></li>
            <li><a href="elements.html"><span class="glyphicons glyphicons-paperclip"></span> Elements</a></li>
            <li><a href="charts.html"><span class="glyphicons glyphicons-stats"></span> Charts</a></li>
            <li><a href="tabs.html"><span class="glyphicons glyphicons-adjust"></span> Tabs</a></li>
            <li><a href="grid.html"><span class="glyphicons glyphicons-show_big_thumbnails"></span> Grid</a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideTwo"><span class="glyphicons glyphicons-vcard"></span><span class="sidebar-title">Form Elements</span><span class="caret"></span></a>
          <ul id="sideTwo" class="nav sub-nav">
            <li><a href="forms.html"><span class="glyphicons glyphicons-link"></span> Form Elements</a></li>
            <li><a href="validation.html"><span class="glyphicons glyphicons-ok"></span> Form Validation</a></li>
            <li><a href="wizard.html"><span class="glyphicons glyphicons-magic"></span> Form Wizard</a></li>
            <li><a href="editors.html"><span class="glyphicons glyphicons-pencil"></span> Editors</a></li>
            <li><a href="editable.html"><span class="glyphicons glyphicons-edit"></span> Inline Editing</a></li>
            <li><a href="xedit.html"><span class="glyphicons glyphicons-check"></span> X-editable</a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideThree"><span class="glyphicons glyphicons-table"></span><span class="sidebar-title">Tables</span><span class="caret"></span></a>
          <ul id="sideThree" class="nav sub-nav">
            <li><a href="tables.html"><span class="glyphicons glyphicons-justify"></span> Tables</a></li>
            <li><a href="datatables.html"><span class="glyphicons glyphicons-list"></span> DataTables</a></li>
            <li><a href="pricing-tables.html"><span class="glyphicons glyphicons-usd"></span> Pricing Tables</a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideFour"><span class="glyphicons glyphicons-cargo"></span><span class="sidebar-title">File Managers</span><span class="caret"></span></a>
          <ul id="sideFour" class="nav sub-nav">
            <li><a href="file-manager.html"><span class="glyphicons glyphicons-cloud"></span> File Manager</a></li>
            <li><a href="upload-tools.html"><span class="glyphicons glyphicons-cloud-upload"></span> File Uploaders</a></li>
            <li><a href="dynamic-gallery.html"><span class="glyphicons glyphicons-picture"></span> Dynamic Gallery</a></li>
            <li><a href="image-tools.html"><span class="glyphicons glyphicons-camera"></span> Image Tools</a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideFive"><span class="glyphicons glyphicons-magic"></span><span class="sidebar-title">Extras</span><span class="caret"></span></a>
          <ul id="sideFive" class="nav sub-nav">
            <li><a href="icons.html"><span class="glyphicons glyphicons-flash"></span> Icons</a></li>
            <li><a href="animations.html"><span class="glyphicons glyphicons-fire"></span> Animations</a></li>
            <li><a href="sliders.html"><span class="glyphicons glyphicons-retweet"></span> Sliders</a></li>
            <li><a href="sketchpad.html"><span class="glyphicons glyphicons-vector_path_square"></span> Sketchpad</a></li>
          </ul>
        </li>
        <li> <a href="maps.html"><span class="glyphicons glyphicons-globe"></span><span class="sidebar-title">Maps</span></a> </li>
        <li> <a href="widgets.html"><span class="glyphicons glyphicons-restart"></span><span class="sidebar-title">Widgets</span></a> </li>
        <li class="active"> <a class="accordion-toggle menu-open" href="#sideSix"><span class="glyphicons glyphicons-book_open"></span><span class="sidebar-title">Pages</span><span class="caret"></span></a>
          <ul id="sideSix" class="nav sub-nav menu-open">
            <li><a href="invoice-page.html"><span class="glyphicons glyphicons glyphicons-print"></span> Printable Invoice</a></li>
            <li><a href="timeline.html"><span class="glyphicons glyphicons-film"></span> Timeline</a></li>
            <li><a href="gallery.html"><span class="glyphicons glyphicons-picture"></span> Gallery</a></li>
            <li><a href="calendar.html"><span class="glyphicons glyphicons-calendar"></span> Calendar</a></li>
            <li class="active"><a href="messages.html"><span class="glyphicons glyphicons-envelope"></span> Messages</a></li>
            <li><a href="profile.html"><span class="glyphicons glyphicons-user"></span> User Profile</a></li>
          </ul>
        </li>
        <li> <a class="accordion-toggle" href="#sideSeven"><span class="glyphicons glyphicons-warning_sign"></span><span class="sidebar-title">Utility Pages</span><span class="caret"></span></a>
          <ul id="sideSeven" class="nav sub-nav">
            <li><a href="faq.html"><span class="glyphicons glyphicons-edit"></span> Faq Page</a></li>
            <li><a href="login.html"><span class="glyphicons glyphicons-power"></span> Login Page</a></li>
            <li><a href="screen-lock.html"><span class="glyphicons glyphicons-lock"></span> Screen Lock</a></li>
            <li><a href="coming-soon.html"><span class="glyphicons glyphicons-road"></span> Coming Soon</a></li>
            <li><a href="404-page.html"><span class="glyphicons glyphicons-circle_remove"></span> 404 Page</a></li>
            <li><a href="500-page.html"><span class="glyphicons glyphicons-circle_exclamation_mark"></span> 500 Page</a></li>
            <li><a href="blank.html"><span class="glyphicons glyphicons-unchecked"></span> Blank Page</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </aside>