<!-- Core Javascript - via CDN --> 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> 
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script> 
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script> 

<!-- Theme Javascript --> 
<script type="text/javascript" src="/skin/default/theme_stardom/js/uniform.min.js"></script> 
<script type="text/javascript" src="/skin/default/theme_stardom/js/main.js"></script>
<script type="text/javascript" src="/skin/default/theme_stardom/js/custom.js"></script> 