<div class="form-group animated fadeInDown" id="password-strength-meter"
	style="display: none;">
	<span class="label label-inverse margin-right-sm" data-toggle="tooltip"
		data-placement="top"
		data-original-title="<?= $this->T('Front:StrongPassword')?>"><i
		class="fa fa-question-circle"></i> <?= $this->T('Front:WhatIsStrongPassword')?></span>
	<div class="progress progress-striped active">
		<div id="result" class="progress-bar" role="progressbar"
			aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
			style="width: 0%"></div>
	</div>
</div>