<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- Meta, title, CSS, favicons, etc. -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle() ?>
<meta name="keywords" content="HTML5 Bootstrap 3 Admin Template UI Theme" />
<meta name="description" content="Stardom - A Responsive HTML5 Admin UI Template Theme">
<meta name="author" content="Siwei">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Start: Load core css -->
<?php echo $this->render('/blocks/css.phtml') ?>
<!-- End: Load core css -->

<!-- Start: Load custom css -->
<?php echo $this->cssHelper() ?> 
<!-- End: Load custom css -->

<!-- Start: Load core icon -->
<?php echo $this->render('/blocks/icon.phtml') ?>
<!-- End: Load core icon -->

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

</head>
 
<!-- Start: Load Content -->
<?php echo $this->layout()->content ?>
<!-- End: Load Content -->

<!-- Start: Load core javascript -->
<?php echo $this->render('/blocks/javascript.phtml') ?>
<!-- End: Load core javascript -->

<!-- Start: Load custom javascript -->
<?php echo $this->javascriptHelper() ?> 
<!-- End: Load custom javascript -->


</html>