<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- Meta, title, CSS, favicons, etc. -->
<?= $this->partial('partials/meta.phtml', array(
    'ContentType' => 'text/html; charset=iso-8859-1',
    'keywords' => 'HTML5 Bootstrap 3 Admin Template UI Theme',
    'description' => 'Stardom - A Responsive HTML5 Admin UI Template Theme',
    'author' => 'Siwei Mu',
    'viewport' => 'width=device-width, initial-scale=1.0'
        )) ?>

<?= $this->headTitle() ?>

<!-- Start: Load core css -->
<?= $this->render('/resources/css.phtml') ?>
<!-- End: Load core css -->


<!-- Start: Load custom css -->
<?= $this->cssHelper() ?> 
<!-- End: Load custom css -->


<!-- Start: Load core icon -->
<?= $this->render('/resources/icon.phtml') ?>
<!-- End: Load core icon -->


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
</head>

<body class="<?= $this->placeholder('bodyClass');?>">

<!-- Start: Page header -->
<?php if ($this->placeholder('hasHeader') != '0'):?>
<?= $this->render('/blocks/header.phtml') ?>
<?php endif ?>
<!-- End: Page header -->

<div id="main">

<!-- Start: Sidebar -->
<?php if ($this->placeholder('hasSidebar') != '0'):?>
<?= $this->render('/blocks/sidebar.phtml') ?>
<?php endif ?>
<!-- End: Page header -->

<!-- Start: Flash messenger -->
<?= !empty($this->alert) ? '<div class="error">' . implode('<br />', $this->alert) .'</div>' : null ?>
<!-- End: Flash messenger -->

<!-- Start: Breadcrumb and Content -->
<?php if ($this->placeholder('hasContent') != '0'):?>
<?= $this->render('/blocks/content.phtml') ?>
<?php endif ?>
<!-- End: Breadcrumb and Content -->

</div>

<!-- Begin: Front Page Loading Animation --> 
<div id="page-loader"><span class="glyphicon glyphicon-cog fa-spin cog-1"></span></div>
<!-- End: Front Page Loading Animation --> 

<!-- Start: Load core javascript -->
<?= $this->render('/resources/javascript.phtml') ?>
<!-- End: Load core javascript -->

<script>
jQuery(document).ready(function() {

	// Init Theme Core 	  
	Core.init();   
	
});
</script>

<!-- Start: Load custom javascript -->
<?= $this->javascriptHelper() ?> 
<!-- End: Load custom javascript -->

</body>

</html>